@startuml

database "h2" as db {
	entity city {
		citycode : String
		cityname : String
		path : String
		lng : Double
		lat : Double
	}
}
note bottom of db : spring.datasource.url=jdbc:h2:mem:taskdb\nspring.jpa.hibernate.ddl-auto=none

class City <<Entity>> {
  + id : Long
  - citycode : String
  - cityname : String
  - path : String
  - lng : Double
  - lat : Double
}
City .. city

interface CityRepository <<Repository>> {
	findByCitycode(String)
	deleteByCitycode(String)
}

class CityController <<Controller>> {
  - repository : CityRepository
  + showList(model)
  + addCity(city)
  + process(city, result)
  + editCity(id, model)
  + deleteCity(id)
}

interface CommandLineRunner

class DataLoader <<Component>> {
  - repository : CityRepository
  + run()
}

CityRepository <|-- City
DataLoader *-- CityRepository
CommandLineRunner <|-- DataLoader

CityController *-- CityRepository
@enduml

