@startuml

[*] --> sidebar

state sidebar {
	state "ユーザ管理" as users
	state "ユーザ一覧\n[Role=admin]" as list_
	state "ログイン" as login_
	state "ログアウト" as logout
	state "BLDGデータリスト" as indeies
	state "BLDGデータ登録" as add
	logout --> logout : /logout
}

state "login" as login {
	login : Username
	login : Password
}

state "register" as register {
	register : username
	register : password
	register : email
	register : admin
}

login_ --> login : /login
login --> login : [!success]
sidebar <-- login : [success]
login --> register : /register 新規登録

state user {
	user : username
	user : role
}
users --> user : /user

state "ユーザ一覧" as list {
	state ユーザ {
		ユーザ : id
		ユーザ : username
		ユーザ : email
		ユーザ : role
	}
}
list_ --> list : /admin/list

state cities
	cities : *{citycode}
	cities : *{cityname}
	cities : *{path}
}
indeies --> cities : /city

state form {
	state city {
		city : citycode
		city : cityname
		city : path
	}
}

cities --> cities : /city/delete/{citycode}
cities --> form : /city/edit/{citycode}
add --> form : /city/add
form --> sidebar : [!hasErrors]
form --> form : [hasErrors]

@enduml