@startuml

[*] --> sidebar

state sidebar {
	state "ユーザ管理" as users
	state "ログイン" as login
	state "ログアウト" as logout
	state "BLDGデータリスト" as indeies
	state "BLDGデータ登録" as add
}

state "Sign in" as signin {
	signin : Username
	signin : Password
}
login --> signin : /login
signin --> signin : [!success]
sidebar <-- signin : [success]

state cities
	cities : *{citycode}
	cities : *{cityname}
	cities : *{path}
}
indeies --> cities : /city

state form {
	state city {
		city : citycode
		city : cityname
		city : path
	}
}

state user {
	user : username
	user : role
}
users --> user : /user

cities --> cities : /city/delete/{citycode}
cities --> form : /city/edit/{citycode}
add --> form : /city/add
form --> sidebar : [!hasErrors]
form --> form : [hasErrors]

@enduml