@startuml

[*] --> sidebar

state sidebar {
	state "ユーザ管理" as users
	state "ユーザ一覧\n[Role=admin]" as list_
	state "ログイン" as login_
	state "ログアウト" as logout
	state "BLDGデータリスト" as indeies
	state "BLDGデータ登録" as add
	state "都道府県" as pref
	logout --> logout : /logout
}
indeies --> cities : /city

state "login" as login {
	login : Username
	login : Password
}

state "register.html" as register {
	state "user" as register_user {
		register_user : username
		register_user : password
		register_user : email
		register_user : admin
	}
}

login_ --> login : /login
login --> login : [!success]
sidebar <-- login : [success]
login --> register : /register 新規登録

state user {
	user : username
	user : role
}
users --> user : /user

state "ユーザ一覧" as list {
	state ユーザ {
		ユーザ : id
		ユーザ : username
		ユーザ : email
		ユーザ : role
	}
}
list_ --> list : /admin/list

state cities {
	state city_list {
		city_list : *{citycode}
		city_list : *{cityname}
		city_list : *{path}
	}
}
cities --> cities : /city/delete/{citycode}
cities --> form : /city/edit/{citycode}
cities --> meshes : /mesh/{citycode}

state meshes {
	state mesh_list
}

state tasks {
	state task_履歴
}

state task {
	task : citycode
	task : meshcode
	task : operation
	task : username
	task : updateTime
}

meshes --> tasks : /tasks
tasks --> task : /task
tasks <-- task : /tasks

state form {
	state city {
		city : citycode
		city : cityname
		city : path
	}
}

state "preflist.html" as preflist {
	state pref_list {
		pref_list : *{prefcode}
		pref_list : *{prefname}
		pref_list : *{Point}
	}
}
pref --> preflist : /pref

add --> form : /city/add
form --> sidebar : [!hasErrors]
form --> form : [hasErrors]

@enduml