@startuml

state "準備中" as PREPARATION #FFFFFF {
}

state "受付中" as ACCEPTING #orange {
}

state "NG" as NG #red {
}

state "予約済み" as RESERVED #yellow {
	RESERVED : 編集者
}

state "インポート済み" as IMPORTED #lightgreen {
	IMPORTED : 編集者
	IMPORTED : 変更セットNo
}

state "完了" as END #green {
	END : 編集者
	END : 変更セットNo
	END : 検証者
}

[*] --> PREPARATION
PREPARATION --> ACCEPTING
ACCEPTING --> RESERVED	: タスク予約
NG --> RESERVED	: タスク予約
ACCEPTING --> IMPORTED	: 編集完了
NG --> IMPORTED	: 編集完了
RESERVED --> IMPORTED	: 編集完了
IMPORTED --> IMPORTED	: 編集完了
ACCEPTING <- RESERVED	: タスク予約取消

IMPORTED --> END	: 検証結果[OK]
NG <- IMPORTED		: 検証結果[NG]

@enduml